[build]
  base = "."
  publish = "dist"
  command = "CI=false npm run build"

[dev]
  command = "npm start"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
